### ISSUE TITLE
Arabic words are not appearing

### ISSUE THREAD

**Issue by abedelrahmanOpenTech** [selvam920/drago_blue_printer#1]
I am trying to print arabic words but its not working, I tried to put charset utf8 but still not working, what is the solution?

**Comment by rabihmb** [comment]
The Arabic words are not shown, and getting the following error when trying to build on IOS

`No podspec found for `drago_blue_printer` in `.symlinks/plugins/drago_blue_printer/ios``

here is the full error code when trying to build:

> Running pod install...                                             330ms
> CocoaPods' output:
> ↳
>       Preparing
> 
>     Analyzing dependencies
> 
>     Inspecting targets to integrate
>       Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
> 
>     Fetching external sources
>     -> Fetching podspec for `Flutter` from `Flutter`
>     -> Fetching podspec for `app_settings` from `.symlinks/plugins/app_settings/ios`
>     -> Fetching podspec for `connectivity_plus` from `.symlinks/plugins/connectivity_plus/ios`
>     -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
>     -> Fetching podspec for `drago_blue_printer` from `.symlinks/plugins/drago_blue_printer/ios`
>     [!] No podspec found for `drago_blue_printer` in `.symlinks/plugins/drago_blue_printer/ios`
> 
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/external_sources/path_source.rb:14:in `block
>     in fetch'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/external_sources/path_source.rb:11:in
>     `fetch'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:993:in
>     `fetch_external_source'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:972:in `block (2
>     levels) in fetch_external_sources'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:971:in `each'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:971:in `block in
>     fetch_external_sources'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:970:in
>     `fetch_external_sources'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in
>     resolve_dependencies'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
>     /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'
> 
> Error running pod install
